version: '3'

services:
  db:
    image: postgres:latest
    container_name: "postgres_12"
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
