version: '3'

services:
  mongo:
    image: mongo:3.4
    container_name: "mongo_34"
    # image: mongo:4.2.8
    # container_name: "mongo_428"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes: 
      - ./data:/data/db
